# Generated by Django 5.2 on 2025-04-25 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_contenido_post_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='comment',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en el carrusel principal'),
        ),
        migrations.AddField(
            model_name='post',
            name='mostrar_en_encabezado',
            field=models.BooleanField(default=False, help_text='Mostrar en el carrusel del encabezado'),
        ),
        migrations.AddField(
            model_name='post',
            name='orden_carrusel',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (mayor número = más adelante)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CarruselEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('velocidad_transicion', models.PositiveIntegerField(default=5000, help_text='Velocidad de transición entre slides en milisegundos')),
                ('efecto_transicion', models.CharField(choices=[('desvanecimiento', 'Desvanecimiento'), ('deslizamiento', 'Deslizamiento')], default='desvanecimiento', max_length=20)),
                ('posts', models.ManyToManyField(blank=True, help_text='Posts para mostrar en el carrusel', limit_choices_to={'mostrar_en_encabezado': True}, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('enlace', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('carrusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_personalizadas', to='blog.carruselencabezado')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
