# Generated by Django 5.2 on 2025-04-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_comment_aprobado_post_destacado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagencarrusel',
            name='carrusel',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='mostrar_en_encabezado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='orden_carrusel',
        ),
        migrations.AddField(
            model_name='post',
            name='mostrar_en_carrusel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CarruselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='blog.post')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='CarruselEncabezado',
        ),
        migrations.DeleteModel(
            name='ImagenCarrusel',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
