# Generated by Django 5.2 on 2025-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_imagencarrusel_carrusel_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sitio', models.CharField(default='Marmorten Production', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(upload_to='equipo/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['orden'],
            },
        ),
    ]
