# Generated by Django 5.2 on 2025-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_configuracionsitio_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='email_contacto',
            field=models.EmailField(default='contacto@marmoten.com', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='sobre_nosotros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='titulo_sitio',
            field=models.CharField(default='Marmoten Production', max_length=200),
        ),
    ]
