# Generated by Django 5.2 on 2025-04-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_configuracionsitio_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='banner_sobre_nosotros',
            field=models.ImageField(blank=True, null=True, upload_to='config/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='icono_mision',
            field=models.ImageField(blank=True, null=True, upload_to='config/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='icono_vision',
            field=models.ImageField(blank=True, null=True, upload_to='config/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_sobre_nosotros',
            field=models.ImageField(blank=True, null=True, upload_to='config/'),
        ),
        migrations.CreateModel(
            name='ImagenGaleriaSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_sobre_nosotros/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_sobre_nosotros', to='blog.configuracionsitio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
