# Generated by Django 5.2 on 2025-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_configuracionsitio_banner_sobre_nosotros_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagengaleriasobrenosotros',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Galería Sobre Nosotros'},
        ),
        migrations.AddField(
            model_name='imagengaleriasobrenosotros',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='banner_sobre_nosotros',
            field=models.ImageField(blank=True, help_text="Banner para la página 'Sobre Nosotros' (1920x500px recomendado)", null=True, upload_to='config/sobre_nosotros/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='icono_mision',
            field=models.ImageField(blank=True, help_text='Icono para la sección Misión (200x200px recomendado)', null=True, upload_to='config/iconos/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='icono_vision',
            field=models.ImageField(blank=True, help_text='Icono para la sección Visión (200x200px recomendado)', null=True, upload_to='config/iconos/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='imagen_sobre_nosotros',
            field=models.ImageField(blank=True, help_text="Imagen descriptiva para 'Sobre Nosotros' (800x600px recomendado)", null=True, upload_to='config/sobre_nosotros/'),
        ),
    ]
