# Generated by Django 5.2 on 2025-04-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_imagengaleriasobrenosotros_options_and_more'),
    ]

    operations = [
    ]
