# Generated by Django 5.2 on 2025-04-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20250427_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionPersonalizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('CAROUSEL', 'Carrusel'), ('ENLACE', 'Enlace')], max_length=10)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='secciones/')),
                ('enlace_url', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('formato_texto', models.CharField(choices=[('NORMAL', 'Normal'), ('NEGRITA', 'Negrita'), ('CURSIVA', 'Cursiva')], default='NORMAL', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Secciones editables',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='blog.seccionpersonalizable')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
