# Generated by Django 5.2 on 2025-04-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_seccionpersonalizable_imagencarrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('CAROUSEL', 'Carrusel de imágenes')], max_length=10)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sobre_nosotros/secciones/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Secciones Sobre Nosotros',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='imagencarrusel',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Imágenes para Carruseles'},
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen',
            field=models.ImageField(upload_to='sobre_nosotros/carrusel/'),
        ),
        migrations.CreateModel(
            name='ImagenCarruselSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sobre_nosotros/carrusel/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='blog.seccionsobrenosotros')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_del_carrusel', to='blog.seccionsobrenosotros'),
        ),
    ]
