# Generated by Django 5.2 on 2025-04-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_seccionsobrenosotros_alter_imagencarrusel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeccionPersonalizable',
        ),
    ]
