# Generated by Django 5.2 on 2025-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_seccionpersonalizable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='seccionsobrenosotros',
            name='tipo',
            field=models.CharField(choices=[('PORTADA', 'Portada (solo una)'), ('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('CAROUSEL', 'Carrusel de imágenes')], max_length=10),
        ),
    ]
