# Generated by Django 5.2 on 2025-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_mensajecontacto_alter_seccionsobrenosotros_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enlace a contenido externo', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_enlace',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter/X'), ('OTRO', 'Otro')], help_text='Tipo de enlace externo', max_length=10, null=True),
        ),
    ]
