# Generated by Django 5.2 on 2025-05-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_enlace_externo_post_tipo_enlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tipo_enlace', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter/X'), ('OTRO', 'Otro')], max_length=10)),
                ('mostrar_video', models.BooleanField(default=True, help_text='Mostrar video embebido (solo para YouTube)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='blog.post')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
