# Generated by Django 5.2 on 2025-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_enlaceexterno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='enlace_externo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tipo_enlace',
        ),
        migrations.AddField(
            model_name='post',
            name='enlaces_externos',
            field=models.JSONField(blank=True, default=list, help_text="Lista de enlaces externos en formato [{'url': '', 'tipo': 'YOUTUBE', 'mostrar_video': True}]"),
        ),
        migrations.DeleteModel(
            name='EnlaceExterno',
        ),
    ]
