# Generated by Django 5.2 on 2025-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_enlace_externo_remove_post_tipo_enlace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='enlaces_externos',
            field=models.JSONField(blank=True, default=list, help_text='Formato JSON: [{\n            "url": "https://ejemplo.com", \n            "tipo": "YOUTUBE", \n            "mostrar_video": true\n        }]'),
        ),
    ]
