# Generated by Django 5.2 on 2025-05-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_enlaces_externos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='enlaces_externos',
        ),
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter/X'), ('OTRO', 'Otro')], max_length=10)),
                ('mostrar', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_externos', to='blog.post')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
