# Generated by Django 5.2 on 2025-05-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_enlaces_externos_enlaceexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceexterno',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_externos', to='blog.equipo'),
        ),
        migrations.AlterField(
            model_name='enlaceexterno',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_externos', to='blog.post'),
        ),
    ]
