# Generated by Django 5.2 on 2025-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_enlaceexterno_equipo_alter_enlaceexterno_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
