# Generated by Django 5.2 on 2025-05-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_configuracionsitio_telefono_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='telefono_contacto',
        ),
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Oficina, Móvil, WhatsApp', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='blog.configuracionsitio')),
            ],
            options={
                'verbose_name_plural': 'Teléfonos de Contacto',
                'ordering': ['orden'],
            },
        ),
    ]
