# Generated by Django 5.2 on 2025-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_configuracionsitio_telefono_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imb_url',
            field=models.URLField(blank=True),
        ),
    ]
