# Generated by Django 5.2 on 2025-05-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_configuracionsitio_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionsobrenosotros',
            name='tipo',
            field=models.CharField(choices=[('PORTADA', 'Portada (solo una)'), ('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('CAROUSEL', 'Carrusel de imágenes'), ('REDES', 'Enlaces/Redes Sociales')], max_length=10),
        ),
        migrations.CreateModel(
            name='EnlaceSeccionSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter/X'), ('IMDB', 'IMDb'), ('OTRO', 'Otro')], max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('icono', models.ImageField(blank=True, help_text='Icono personalizado (opcional). Si no se sube, se usará el icono por defecto según el tipo.', null=True, upload_to='sobre_nosotros/iconos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='blog.seccionsobrenosotros')),
            ],
            options={
                'verbose_name': 'Enlace de sección',
                'verbose_name_plural': 'Enlaces de sección',
                'ordering': ['orden'],
            },
        ),
    ]
