# Generated by Django 5.2 on 2025-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_content_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carruselpost',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carruselpost',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carruselpost',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carruselpost',
            name='titulo_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='biografia_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='biografia_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puesto_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puesto_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galeriaimagenes',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galeriaimagenes',
            name='titulo_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen_en',
            field=models.TextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen_es',
            field=models.TextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='contenido_texto_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='contenido_texto_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='titulo_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
