# Generated by Django 5.2 on 2025-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_carruselpost_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
