# Generated by Django 5.2 on 2025-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_configuracionsitio_descripcion_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='biografia_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='biografia_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
