# Generated by Django 5.2 on 2025-05-26 10:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_equipo_biografia_alter_equipo_biografia_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Trabajo',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción (Inglés)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='biografia_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='biografia_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Breve resumen para mostrar en las tarjetas', null=True),
        ),
        migrations.AlterField(
            model_name='seccionsobrenosotros',
            name='contenido_texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccionsobrenosotros',
            name='contenido_texto_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccionsobrenosotros',
            name='contenido_texto_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tipotrabajo', verbose_name='Tipo de trabajo'),
        ),
    ]
