# Generated by Django 5.2 on 2025-05-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_tipotrabajo_alter_configuracionsitio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='carrusel_asociado',
            field=models.ForeignKey(blank=True, help_text='Selecciona un carrusel para mostrar con esta sección', limit_choices_to={'tipo': 'CAROUSEL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.seccionsobrenosotros'),
        ),
        migrations.AddField(
            model_name='seccionsobrenosotros',
            name='posicion_carrusel',
            field=models.CharField(choices=[('DERECHA', 'Derecha'), ('IZQUIERDA', 'Izquierda'), ('NINGUNA', 'Sin carrusel')], default='NINGUNA', help_text='Posición del carrusel respecto al texto', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo_trabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tipotrabajo', verbose_name='Tipo de trabajo'),
        ),
    ]
