# Generated by Django 5.2 on 2025-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_seccionsobrenosotros_carrusel_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabajo',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción (Inglés)'),
        ),
    ]
