# Generated by Django 5.2 on 2025-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_tipotrabajo_nombre_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabajo',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Inglés)'),
        ),
        migrations.AlterField(
            model_name='tipotrabajo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre (Español)'),
        ),
        migrations.AlterField(
            model_name='tipotrabajo',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Inglés)'),
        ),
    ]
